# Constants

ENABLE_VSYNC = True
USING_NETWORK_TABLES = False
ROBOT_LENGTH_REAL_M = 0.9144
ROBOT_HEIGHT_REAL_M = 0.9144
FIELD_WIDTH_IMG = 1500
FIELD_HEIGHT_IMG = 689

FIELD_WIDTH_REAL_CM = 1755
FIELD_WIDTH_REAL_M = FIELD_WIDTH_REAL_CM / 100